#!/usr/bin/env python3
"""Compile a UTF-8 Java properties file into a small Java lookup class."""
import sys
from pathlib import Path


def java_string(value):
    result='"'
    for char in value:
        code=ord(char)
        if char=='\\': result+='\\\\'
        elif char=='"': result+='\\"'
        elif char=='\n': result+='\\n'
        elif char=='\r': result+='\\r'
        elif char=='\t': result+='\\t'
        elif code < 32 or code > 126:
            if code <= 0xffff: result+='\\u%04x' % code
            else:
                code-=0x10000
                result+='\\u%04x\\u%04x' % (0xd800+(code>>10),0xdc00+(code&0x3ff))
        else: result+=char
    return result+'"'


def read_properties(path):
    values={}
    for number,raw in enumerate(Path(path).read_text(encoding='utf-8').splitlines(),1):
        line=raw.strip()
        if not line or line.startswith('#') or line.startswith('!'): continue
        if '=' not in line:
            raise ValueError(f'{path}:{number}: expected key=value')
        key,value=line.split('=',1)
        key=key.strip()
        if not key: raise ValueError(f'{path}:{number}: empty key')
        values[key]=value.strip()
    return values


def generate(values):
    lines=[
        '// Generated from translations/de.properties. Do not edit this file.',
        'package me.jxl.kiosk.plugins.sip;',
        'final class GermanStrings {',
        '    private GermanStrings() { }',
        '    static String get(String key) {',
        '        switch (key) {'
    ]
    for key,value in sorted(values.items()):
        lines.append('            case %s: return %s;' % (java_string(key),java_string(value)))
    lines.extend(['            default: return null;','        }','    }','}'])
    return '\n'.join(lines)+'\n'


if __name__ == '__main__':
    if len(sys.argv)!=3: raise SystemExit('Usage: generate_translations.py <input.properties> <output.java>')
    try:
        values=read_properties(sys.argv[1])
        Path(sys.argv[2]).parent.mkdir(parents=True,exist_ok=True)
        Path(sys.argv[2]).write_text(generate(values),encoding='utf-8')
    except (OSError,ValueError) as error:
        raise SystemExit(str(error))
